// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaF5dAF3gSjU4HJDrp6lSbyHZPP-dEC5I',
    appId: '1:792512183935:web:2ed64d1258e017a10ac94a',
    messagingSenderId: '792512183935',
    projectId: 'geotales-f2ee3',
    authDomain: 'geotales-f2ee3.firebaseapp.com',
    storageBucket: 'geotales-f2ee3.appspot.com',
    measurementId: 'G-8N954DDV6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqgzkR_FN2NTuN2vlakmDDncUc7EDXfOU',
    appId: '1:792512183935:android:09ee72e4d3087e620ac94a',
    messagingSenderId: '792512183935',
    projectId: 'geotales-f2ee3',
    storageBucket: 'geotales-f2ee3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyL7akN0R61Zj2b242c8-UEzrbQcYptec',
    appId: '1:792512183935:ios:be0cfb3fcf9289220ac94a',
    messagingSenderId: '792512183935',
    projectId: 'geotales-f2ee3',
    storageBucket: 'geotales-f2ee3.appspot.com',
    iosClientId: '792512183935-f288771p75lrti4f3qehec394k6tpsm5.apps.googleusercontent.com',
    iosBundleId: 'com.example.geotales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyL7akN0R61Zj2b242c8-UEzrbQcYptec',
    appId: '1:792512183935:ios:c628143170b2df690ac94a',
    messagingSenderId: '792512183935',
    projectId: 'geotales-f2ee3',
    storageBucket: 'geotales-f2ee3.appspot.com',
    iosClientId: '792512183935-ev535m8assq3b6f1fbho6cobic1noft9.apps.googleusercontent.com',
    iosBundleId: 'com.example.geotales.RunnerTests',
  );
}
